/**
 * AWS RDS Cluster Resource Definition (Aurora)
 *
 * Complete schema based on Terraform AWS Provider 5.x
 * https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster
 */

import type { ServiceDefinition } from '../../types';
import { DATABASE_ICONS } from '../icons';

export const awsRdsCluster: ServiceDefinition = {
  id: 'rds_cluster',
  terraform_resource: 'aws_rds_cluster',
  name: 'RDS Cluster',
  description: 'Aurora database cluster with multi-AZ high availability and read replicas',
  icon: DATABASE_ICONS.AURORA,
  category: 'database',
  classification: 'icon',

  inputs: {
    required: [
      {
        name: 'engine',
        type: 'string',
        description: 'The database engine to use',
        options: ['aurora-mysql', 'aurora-postgresql', 'mysql', 'postgres'],
        group: 'basic',
      },
    ],

    optional: [
      {
        name: 'cluster_identifier',
        type: 'string',
        description: 'The cluster identifier (if omitted, Terraform will assign a random unique identifier)',
        validation: { pattern: '^[a-z][a-z0-9-]*$', maxLength: 63 },
        group: 'basic',
      },
      {
        name: 'cluster_identifier_prefix',
        type: 'string',
        description: 'Prefix for auto-generated cluster identifier',
        group: 'basic',
      },
      {
        name: 'engine_version',
        type: 'string',
        description: 'Database engine version',
        group: 'basic',
      },
      {
        name: 'engine_mode',
        type: 'string',
        description: 'Database engine mode',
        default: 'provisioned',
        options: ['provisioned', 'serverless', 'parallelquery', 'global', 'multimaster'],
        group: 'basic',
      },
      {
        name: 'master_username',
        type: 'string',
        description: 'Username for the master DB user',
        group: 'basic',
      },
      {
        name: 'master_password',
        type: 'string',
        description: 'Password for the master DB user',
        sensitive: true,
        group: 'basic',
      },
      {
        name: 'manage_master_user_password',
        type: 'bool',
        description: 'Allow RDS to manage the master user password in Secrets Manager',
        default: false,
        group: 'security',
      },
      {
        name: 'master_user_secret_kms_key_id',
        type: 'string',
        description: 'KMS key ARN for encrypting the master user secret',
        reference: 'aws_kms_key.arn',
        group: 'security',
      },
      {
        name: 'database_name',
        type: 'string',
        description: 'Name for the automatically created database',
        group: 'basic',
      },
      {
        name: 'port',
        type: 'number',
        description: 'Port on which the DB accepts connections',
        group: 'networking',
      },
      {
        name: 'db_subnet_group_name',
        type: 'string',
        description: 'DB subnet group for the cluster',
        reference: 'aws_db_subnet_group.name',
        group: 'networking',
      },
      {
        name: 'vpc_security_group_ids',
        type: 'list(string)',
        description: 'List of VPC security groups to associate',
        reference: 'aws_security_group.id',
        group: 'networking',
      },
      {
        name: 'availability_zones',
        type: 'list(string)',
        description: 'List of EC2 Availability Zones for the cluster',
        group: 'basic',
      },
      {
        name: 'db_cluster_parameter_group_name',
        type: 'string',
        description: 'Cluster parameter group to associate',
        group: 'advanced',
      },
      {
        name: 'db_instance_parameter_group_name',
        type: 'string',
        description: 'Instance parameter group for all cluster instances',
        group: 'advanced',
      },
      {
        name: 'storage_encrypted',
        type: 'bool',
        description: 'Enable cluster encryption',
        default: false,
        group: 'security',
      },
      {
        name: 'kms_key_id',
        type: 'string',
        description: 'ARN for the KMS encryption key',
        reference: 'aws_kms_key.arn',
        group: 'security',
      },
      {
        name: 'storage_type',
        type: 'string',
        description: 'Storage type for the cluster',
        options: ['aurora', 'aurora-iopt1', 'io1'],
        group: 'advanced',
      },
      {
        name: 'allocated_storage',
        type: 'number',
        description: 'Storage in GiB per DB instance (Multi-AZ clusters only)',
        group: 'advanced',
      },
      {
        name: 'iops',
        type: 'number',
        description: 'Provisioned IOPS for Multi-AZ cluster instances',
        group: 'advanced',
      },
      {
        name: 'db_cluster_instance_class',
        type: 'string',
        description: 'Compute and memory capacity per instance (Multi-AZ clusters)',
        group: 'advanced',
      },
      {
        name: 'backup_retention_period',
        type: 'number',
        description: 'Days to retain automated backups (1-35)',
        default: 1,
        validation: { min: 1, max: 35 },
        group: 'advanced',
      },
      {
        name: 'preferred_backup_window',
        type: 'string',
        description: 'Daily backup time window (UTC)',
        example: '02:00-03:00',
        group: 'advanced',
      },
      {
        name: 'preferred_maintenance_window',
        type: 'string',
        description: 'Weekly maintenance window (UTC)',
        example: 'sun:05:00-sun:06:00',
        group: 'advanced',
      },
      {
        name: 'backtrack_window',
        type: 'number',
        description: 'Target backtrack window in seconds (Aurora MySQL only, 0 to disable)',
        default: 0,
        validation: { min: 0, max: 259200 },
        group: 'advanced',
      },
      {
        name: 'skip_final_snapshot',
        type: 'bool',
        description: 'Skip final snapshot before cluster deletion',
        default: false,
        group: 'advanced',
      },
      {
        name: 'final_snapshot_identifier',
        type: 'string',
        description: 'Name of final snapshot on cluster deletion',
        group: 'advanced',
      },
      {
        name: 'copy_tags_to_snapshot',
        type: 'bool',
        description: 'Copy cluster tags to snapshots',
        default: false,
        group: 'advanced',
      },
      {
        name: 'snapshot_identifier',
        type: 'string',
        description: 'Snapshot ID to create the cluster from',
        group: 'advanced',
      },
      {
        name: 'deletion_protection',
        type: 'bool',
        description: 'Enable deletion protection',
        default: false,
        group: 'security',
      },
      {
        name: 'apply_immediately',
        type: 'bool',
        description: 'Apply changes immediately instead of during maintenance window',
        default: false,
        group: 'advanced',
      },
      {
        name: 'allow_major_version_upgrade',
        type: 'bool',
        description: 'Enable major engine version upgrades',
        default: false,
        group: 'advanced',
      },
      {
        name: 'iam_database_authentication_enabled',
        type: 'bool',
        description: 'Enable IAM database authentication',
        default: false,
        group: 'security',
      },
      {
        name: 'iam_roles',
        type: 'list(string)',
        description: 'List of IAM Role ARNs to associate with the cluster',
        group: 'security',
      },
      {
        name: 'enabled_cloudwatch_logs_exports',
        type: 'list(string)',
        description: 'Log types to export to CloudWatch',
        options: ['audit', 'error', 'general', 'slowquery', 'postgresql'],
        group: 'advanced',
      },
      {
        name: 'enable_http_endpoint',
        type: 'bool',
        description: 'Enable HTTP endpoint (Data API)',
        default: false,
        group: 'advanced',
      },
      {
        name: 'enable_global_write_forwarding',
        type: 'bool',
        description: 'Enable write forwarding to global cluster',
        default: false,
        group: 'advanced',
      },
      {
        name: 'enable_local_write_forwarding',
        type: 'bool',
        description: 'Enable local write forwarding to writer instance',
        default: false,
        group: 'advanced',
      },
      {
        name: 'global_cluster_identifier',
        type: 'string',
        description: 'Global cluster identifier',
        group: 'advanced',
      },
      {
        name: 'replication_source_identifier',
        type: 'string',
        description: 'ARN of source cluster for read replica',
        group: 'advanced',
      },
      {
        name: 'source_region',
        type: 'string',
        description: 'Source region for encrypted cross-region replica',
        group: 'advanced',
      },
      {
        name: 'network_type',
        type: 'string',
        description: 'Cluster network type',
        options: ['IPV4', 'DUAL'],
        group: 'networking',
      },
      {
        name: 'performance_insights_enabled',
        type: 'bool',
        description: 'Enable Performance Insights',
        default: false,
        group: 'advanced',
      },
      {
        name: 'performance_insights_kms_key_id',
        type: 'string',
        description: 'KMS key ARN for Performance Insights encryption',
        reference: 'aws_kms_key.arn',
        group: 'security',
      },
      {
        name: 'performance_insights_retention_period',
        type: 'number',
        description: 'Days to retain Performance Insights data',
        default: 7,
        group: 'advanced',
      },
      {
        name: 'delete_automated_backups',
        type: 'bool',
        description: 'Delete automated backups after cluster deletion',
        default: true,
        group: 'advanced',
      },
      {
        name: 'tags',
        type: 'map(string)',
        description: 'Tags to apply to the cluster',
        default: {},
        group: 'basic',
      },
    ],

    blocks: [
      {
        name: 'scaling_configuration',
        description: 'Scaling configuration for Serverless v1',
        required: false,
        multiple: false,
        attributes: [
          {
            name: 'auto_pause',
            type: 'bool',
            description: 'Enable automatic pause after seconds_until_auto_pause',
            default: true,
          },
          {
            name: 'min_capacity',
            type: 'number',
            description: 'Minimum Aurora capacity units',
          },
          {
            name: 'max_capacity',
            type: 'number',
            description: 'Maximum Aurora capacity units',
          },
          {
            name: 'seconds_until_auto_pause',
            type: 'number',
            description: 'Seconds before auto-pause (300-86400)',
            default: 300,
          },
          {
            name: 'seconds_before_timeout',
            type: 'number',
            description: 'Seconds before enforcing timeout action (60-600)',
          },
          {
            name: 'timeout_action',
            type: 'string',
            description: 'Action when timeout is reached',
            options: ['ForceApplyCapacityChange', 'RollbackCapacityChange'],
          },
        ],
      },
      {
        name: 'serverlessv2_scaling_configuration',
        description: 'Scaling configuration for Serverless v2',
        required: false,
        multiple: false,
        attributes: [
          {
            name: 'min_capacity',
            type: 'number',
            description: 'Minimum capacity in ACUs (0-256 in 0.5 steps)',
          },
          {
            name: 'max_capacity',
            type: 'number',
            description: 'Maximum capacity in ACUs (0-256 in 0.5 steps)',
          },
          {
            name: 'seconds_until_auto_pause',
            type: 'number',
            description: 'Seconds before auto-pause (300-86400)',
          },
        ],
      },
      {
        name: 's3_import',
        description: 'S3 import configuration for database initialization',
        required: false,
        multiple: false,
        attributes: [
          {
            name: 'bucket_name',
            type: 'string',
            description: 'S3 bucket containing the backup',
          },
          {
            name: 'bucket_prefix',
            type: 'string',
            description: 'Path to backup in S3 bucket',
          },
          {
            name: 'ingestion_role',
            type: 'string',
            description: 'IAM role ARN for data loading',
          },
          {
            name: 'source_engine',
            type: 'string',
            description: 'Source database engine',
          },
          {
            name: 'source_engine_version',
            type: 'string',
            description: 'Source engine version',
          },
        ],
      },
      {
        name: 'restore_to_point_in_time',
        description: 'Point-in-time restore configuration',
        required: false,
        multiple: false,
        attributes: [
          {
            name: 'source_cluster_identifier',
            type: 'string',
            description: 'Source cluster identifier or ARN',
          },
          {
            name: 'source_cluster_resource_id',
            type: 'string',
            description: 'Source cluster resource ID (for deleted cluster)',
          },
          {
            name: 'restore_type',
            type: 'string',
            description: 'Restore type',
            options: ['full-copy', 'copy-on-write'],
          },
          {
            name: 'restore_to_time',
            type: 'string',
            description: 'UTC timestamp to restore to',
          },
          {
            name: 'use_latest_restorable_time',
            type: 'bool',
            description: 'Restore to the latest restorable time',
            default: false,
          },
        ],
      },
    ],
  },

  outputs: [
    { name: 'id', type: 'string', description: 'RDS Cluster Identifier' },
    { name: 'arn', type: 'string', description: 'ARN of the cluster' },
    { name: 'cluster_identifier', type: 'string', description: 'RDS Cluster Identifier' },
    { name: 'cluster_resource_id', type: 'string', description: 'RDS Cluster Resource ID' },
    { name: 'cluster_members', type: 'list(string)', description: 'List of RDS Instances in the cluster' },
    { name: 'endpoint', type: 'string', description: 'DNS address of the writer instance' },
    { name: 'reader_endpoint', type: 'string', description: 'Read-only endpoint (load-balanced)' },
    { name: 'port', type: 'number', description: 'Database port' },
    { name: 'database_name', type: 'string', description: 'Created database name' },
    { name: 'master_username', type: 'string', description: 'Master database user name' },
    { name: 'engine_version_actual', type: 'string', description: 'Running database version' },
    { name: 'hosted_zone_id', type: 'string', description: 'Route53 Hosted Zone ID' },
    { name: 'availability_zones', type: 'list(string)', description: 'Availability zones' },
    { name: 'master_user_secret', type: 'object', description: 'Master user secret details' },
    { name: 'tags_all', type: 'map(string)', description: 'All tags including provider defaults' },
  ],

  terraform: {
    resourceType: 'aws_rds_cluster',
    requiredArgs: ['engine'],
    referenceableAttrs: {
      id: 'id',
      arn: 'arn',
      endpoint: 'endpoint',
      reader_endpoint: 'reader_endpoint',
      cluster_resource_id: 'cluster_resource_id',
      port: 'port',
    },
  },

  relations: {
    containmentRules: [],
    edgeRules: [
      {
        whenEdgeKind: 'attach',
        direction: 'outbound',
        toResourceType: 'aws_security_group',
        apply: [{ pushToListArg: 'vpc_security_group_ids', toTargetAttr: 'id' }],
      },
      {
        whenEdgeKind: 'attach',
        direction: 'outbound',
        toResourceType: 'aws_db_subnet_group',
        apply: [{ setArg: 'db_subnet_group_name', toTargetAttr: 'name' }],
      },
      {
        whenEdgeKind: 'attach',
        direction: 'outbound',
        toResourceType: 'aws_kms_key',
        apply: [{ setArg: 'kms_key_id', toTargetAttr: 'arn' }],
      },
    ],
    autoResolveRules: [],
  },
};
