/**
 * AWS RDS DB Instance Resource Definition
 *
 * Complete schema based on Terraform AWS Provider 5.x
 * https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance
 */

import type { ServiceDefinition } from '../../types';
import { DATABASE_ICONS } from '../icons';

export const awsDbInstance: ServiceDefinition = {
  id: 'db_instance',
  terraform_resource: 'aws_db_instance',
  name: 'RDS Instance',
  description: 'Managed relational database instance supporting MySQL, PostgreSQL, MariaDB, Oracle, and SQL Server',
  icon: DATABASE_ICONS.RDS,
  category: 'database',
  classification: 'icon',

  inputs: {
    required: [
      {
        name: 'identifier',
        type: 'string',
        description: 'The name of the RDS instance. If omitted, Terraform will assign a random unique identifier',
        validation: { pattern: '^[a-z][a-z0-9-]*$', maxLength: 63 },
        group: 'basic',
      },
      {
        name: 'instance_class',
        type: 'string',
        description: 'The instance type of the RDS instance (e.g., db.t3.micro)',
        example: 'db.t3.micro',
        options: [
          'db.t3.micro', 'db.t3.small', 'db.t3.medium', 'db.t3.large', 'db.t3.xlarge', 'db.t3.2xlarge',
          'db.t4g.micro', 'db.t4g.small', 'db.t4g.medium', 'db.t4g.large', 'db.t4g.xlarge', 'db.t4g.2xlarge',
          'db.m5.large', 'db.m5.xlarge', 'db.m5.2xlarge', 'db.m5.4xlarge', 'db.m5.8xlarge', 'db.m5.12xlarge',
          'db.m6g.large', 'db.m6g.xlarge', 'db.m6g.2xlarge', 'db.m6g.4xlarge', 'db.m6g.8xlarge',
          'db.r5.large', 'db.r5.xlarge', 'db.r5.2xlarge', 'db.r5.4xlarge', 'db.r5.8xlarge',
          'db.r6g.large', 'db.r6g.xlarge', 'db.r6g.2xlarge', 'db.r6g.4xlarge', 'db.r6g.8xlarge',
        ],
        group: 'basic',
      },
      {
        name: 'engine',
        type: 'string',
        description: 'The database engine to use',
        options: ['mysql', 'postgres', 'mariadb', 'oracle-ee', 'oracle-se2', 'sqlserver-ee', 'sqlserver-se', 'sqlserver-ex', 'sqlserver-web'],
        group: 'basic',
      },
    ],

    optional: [
      {
        name: 'engine_version',
        type: 'string',
        description: 'The engine version to use. If not specified, the latest version is used',
        group: 'basic',
      },
      {
        name: 'allocated_storage',
        type: 'number',
        description: 'The allocated storage in gibibytes',
        default: 20,
        validation: { min: 20, max: 65536 },
        group: 'basic',
      },
      {
        name: 'max_allocated_storage',
        type: 'number',
        description: 'Maximum storage threshold for autoscaling. Set to 0 to disable',
        validation: { min: 0, max: 65536 },
        group: 'basic',
      },
      {
        name: 'storage_type',
        type: 'string',
        description: 'The storage type for the DB instance',
        default: 'gp2',
        options: ['standard', 'gp2', 'gp3', 'io1', 'io2'],
        group: 'basic',
      },
      {
        name: 'storage_throughput',
        type: 'number',
        description: 'Storage throughput in MiBps (for gp3 only)',
        validation: { min: 125, max: 1000 },
        group: 'advanced',
      },
      {
        name: 'iops',
        type: 'number',
        description: 'The amount of provisioned IOPS (for io1, io2, gp3)',
        validation: { min: 1000, max: 256000 },
        group: 'advanced',
      },
      {
        name: 'username',
        type: 'string',
        description: 'Username for the master DB user',
        group: 'basic',
      },
      {
        name: 'password',
        type: 'string',
        description: 'Password for the master DB user',
        sensitive: true,
        group: 'basic',
      },
      {
        name: 'manage_master_user_password',
        type: 'bool',
        description: 'Allow RDS to manage the master user password in Secrets Manager',
        default: false,
        group: 'security',
      },
      {
        name: 'master_user_secret_kms_key_id',
        type: 'string',
        description: 'KMS key ID to encrypt the master user secret',
        reference: 'aws_kms_key.arn',
        group: 'security',
      },
      {
        name: 'db_name',
        type: 'string',
        description: 'The name of the database to create when the instance is created',
        group: 'basic',
      },
      {
        name: 'db_subnet_group_name',
        type: 'string',
        description: 'DB subnet group to associate with this instance',
        reference: 'aws_db_subnet_group.name',
        group: 'networking',
      },
      {
        name: 'vpc_security_group_ids',
        type: 'list(string)',
        description: 'List of VPC security group IDs to associate',
        reference: 'aws_security_group.id',
        group: 'networking',
      },
      {
        name: 'availability_zone',
        type: 'string',
        description: 'The AZ for the RDS instance',
        group: 'basic',
      },
      {
        name: 'multi_az',
        type: 'bool',
        description: 'Enable Multi-AZ deployment for high availability',
        default: false,
        group: 'advanced',
      },
      {
        name: 'publicly_accessible',
        type: 'bool',
        description: 'Whether the instance is publicly accessible',
        default: false,
        group: 'networking',
      },
      {
        name: 'port',
        type: 'number',
        description: 'The port on which the DB accepts connections',
        group: 'networking',
      },
      {
        name: 'parameter_group_name',
        type: 'string',
        description: 'Name of the DB parameter group to associate',
        reference: 'aws_db_parameter_group.name',
        group: 'advanced',
      },
      {
        name: 'option_group_name',
        type: 'string',
        description: 'Name of the DB option group to associate',
        group: 'advanced',
      },
      {
        name: 'storage_encrypted',
        type: 'bool',
        description: 'Enable storage encryption',
        default: false,
        group: 'security',
      },
      {
        name: 'kms_key_id',
        type: 'string',
        description: 'The ARN for the KMS encryption key',
        reference: 'aws_kms_key.arn',
        group: 'security',
      },
      {
        name: 'backup_retention_period',
        type: 'number',
        description: 'Days to retain backups (0-35)',
        default: 0,
        validation: { min: 0, max: 35 },
        group: 'advanced',
      },
      {
        name: 'backup_window',
        type: 'string',
        description: 'Daily time range for automated backups (UTC)',
        example: '03:00-04:00',
        group: 'advanced',
      },
      {
        name: 'maintenance_window',
        type: 'string',
        description: 'The window for system maintenance (UTC)',
        example: 'Mon:00:00-Mon:03:00',
        group: 'advanced',
      },
      {
        name: 'auto_minor_version_upgrade',
        type: 'bool',
        description: 'Enable automatic minor version upgrades',
        default: true,
        group: 'advanced',
      },
      {
        name: 'allow_major_version_upgrade',
        type: 'bool',
        description: 'Allow major engine version upgrades',
        default: false,
        group: 'advanced',
      },
      {
        name: 'apply_immediately',
        type: 'bool',
        description: 'Apply changes immediately instead of during maintenance window',
        default: false,
        group: 'advanced',
      },
      {
        name: 'deletion_protection',
        type: 'bool',
        description: 'Prevent database from being deleted',
        default: false,
        group: 'security',
      },
      {
        name: 'skip_final_snapshot',
        type: 'bool',
        description: 'Skip creating a final snapshot before deletion',
        default: false,
        group: 'advanced',
      },
      {
        name: 'final_snapshot_identifier',
        type: 'string',
        description: 'Name of final snapshot when instance is deleted',
        group: 'advanced',
      },
      {
        name: 'copy_tags_to_snapshot',
        type: 'bool',
        description: 'Copy tags to snapshots',
        default: false,
        group: 'advanced',
      },
      {
        name: 'snapshot_identifier',
        type: 'string',
        description: 'Snapshot ID to create the instance from',
        group: 'advanced',
      },
      {
        name: 'replicate_source_db',
        type: 'string',
        description: 'Source DB instance ARN for read replica',
        group: 'advanced',
      },
      {
        name: 'performance_insights_enabled',
        type: 'bool',
        description: 'Enable Performance Insights',
        default: false,
        group: 'advanced',
      },
      {
        name: 'performance_insights_retention_period',
        type: 'number',
        description: 'Days to retain Performance Insights data (7, 31, or 731)',
        default: 7,
        options: ['7', '31', '731'],
        group: 'advanced',
      },
      {
        name: 'performance_insights_kms_key_id',
        type: 'string',
        description: 'KMS key ID for Performance Insights encryption',
        reference: 'aws_kms_key.arn',
        group: 'security',
      },
      {
        name: 'monitoring_interval',
        type: 'number',
        description: 'Enhanced Monitoring interval in seconds (0, 1, 5, 10, 15, 30, 60)',
        default: 0,
        options: ['0', '1', '5', '10', '15', '30', '60'],
        group: 'advanced',
      },
      {
        name: 'monitoring_role_arn',
        type: 'string',
        description: 'IAM role ARN for Enhanced Monitoring',
        reference: 'aws_iam_role.arn',
        group: 'advanced',
      },
      {
        name: 'enabled_cloudwatch_logs_exports',
        type: 'list(string)',
        description: 'Log types to export to CloudWatch',
        options: ['postgresql', 'upgrade', 'error', 'general', 'slowquery', 'audit'],
        group: 'advanced',
      },
      {
        name: 'iam_database_authentication_enabled',
        type: 'bool',
        description: 'Enable IAM database authentication',
        default: false,
        group: 'security',
      },
      {
        name: 'license_model',
        type: 'string',
        description: 'License model (varies by engine)',
        options: ['license-included', 'bring-your-own-license', 'general-public-license'],
        group: 'advanced',
      },
      {
        name: 'network_type',
        type: 'string',
        description: 'Network type for the DB instance',
        options: ['IPV4', 'DUAL'],
        group: 'networking',
      },
      {
        name: 'ca_cert_identifier',
        type: 'string',
        description: 'CA certificate identifier for the DB instance',
        group: 'security',
      },
      {
        name: 'character_set_name',
        type: 'string',
        description: 'Character set for Oracle and SQL Server',
        group: 'advanced',
      },
      {
        name: 'timezone',
        type: 'string',
        description: 'Time zone (SQL Server only)',
        group: 'advanced',
      },
      {
        name: 'delete_automated_backups',
        type: 'bool',
        description: 'Delete automated backups after instance deletion',
        default: true,
        group: 'advanced',
      },
      {
        name: 'dedicated_log_volume',
        type: 'bool',
        description: 'Use dedicated log volume',
        default: false,
        group: 'advanced',
      },
      {
        name: 'tags',
        type: 'map(string)',
        description: 'Tags to apply to the instance',
        default: {},
        group: 'basic',
      },
    ],

    blocks: [
      {
        name: 'blue_green_update',
        description: 'Blue/Green Deployment configuration for low-downtime updates',
        required: false,
        multiple: false,
        attributes: [
          {
            name: 'enabled',
            type: 'bool',
            description: 'Enable Blue/Green deployments',
            default: false,
          },
        ],
      },
      {
        name: 'restore_to_point_in_time',
        description: 'Point-in-time restore configuration',
        required: false,
        multiple: false,
        attributes: [
          {
            name: 'source_db_instance_identifier',
            type: 'string',
            description: 'Source DB instance identifier',
          },
          {
            name: 'source_db_instance_automated_backups_arn',
            type: 'string',
            description: 'Source automated backup ARN',
          },
          {
            name: 'source_dbi_resource_id',
            type: 'string',
            description: 'Source DB resource ID',
          },
          {
            name: 'restore_time',
            type: 'string',
            description: 'UTC timestamp to restore to',
          },
          {
            name: 'use_latest_restorable_time',
            type: 'bool',
            description: 'Restore to the latest restorable time',
            default: false,
          },
        ],
      },
      {
        name: 's3_import',
        description: 'S3 import configuration for restoring from backup',
        required: false,
        multiple: false,
        attributes: [
          {
            name: 'bucket_name',
            type: 'string',
            description: 'S3 bucket containing the backup',
          },
          {
            name: 'bucket_prefix',
            type: 'string',
            description: 'Path to backup in S3',
          },
          {
            name: 'ingestion_role',
            type: 'string',
            description: 'IAM role ARN for data loading',
          },
          {
            name: 'source_engine',
            type: 'string',
            description: 'Source database engine',
          },
          {
            name: 'source_engine_version',
            type: 'string',
            description: 'Source engine version',
          },
        ],
      },
    ],
  },

  outputs: [
    { name: 'id', type: 'string', description: 'RDS DBI resource ID' },
    { name: 'arn', type: 'string', description: 'ARN of the RDS instance' },
    { name: 'address', type: 'string', description: 'Hostname of the RDS instance' },
    { name: 'endpoint', type: 'string', description: 'Connection endpoint (address:port)' },
    { name: 'port', type: 'number', description: 'Database port' },
    { name: 'resource_id', type: 'string', description: 'RDS Resource ID' },
    { name: 'status', type: 'string', description: 'RDS instance status' },
    { name: 'hosted_zone_id', type: 'string', description: 'Route 53 hosted zone ID' },
    { name: 'availability_zone', type: 'string', description: 'Availability zone' },
    { name: 'engine_version_actual', type: 'string', description: 'Running database version' },
    { name: 'latest_restorable_time', type: 'string', description: 'Latest point-in-time restore timestamp' },
    { name: 'ca_cert_identifier', type: 'string', description: 'CA certificate identifier' },
    { name: 'master_user_secret', type: 'object', description: 'Master user secret details when manage_master_user_password is enabled' },
  ],

  terraform: {
    resourceType: 'aws_db_instance',
    requiredArgs: ['identifier', 'instance_class', 'engine'],
    referenceableAttrs: {
      id: 'id',
      arn: 'arn',
      endpoint: 'endpoint',
      address: 'address',
      port: 'port',
      resource_id: 'resource_id',
    },
  },

  relations: {
    containmentRules: [
      {
        whenParentResourceType: 'aws_subnet',
        apply: [],
      },
    ],
    edgeRules: [
      {
        whenEdgeKind: 'attach',
        direction: 'outbound',
        toResourceType: 'aws_security_group',
        apply: [{ pushToListArg: 'vpc_security_group_ids', toTargetAttr: 'id' }],
      },
      {
        whenEdgeKind: 'attach',
        direction: 'outbound',
        toResourceType: 'aws_db_subnet_group',
        apply: [{ setArg: 'db_subnet_group_name', toTargetAttr: 'name' }],
      },
      {
        whenEdgeKind: 'attach',
        direction: 'outbound',
        toResourceType: 'aws_db_parameter_group',
        apply: [{ setArg: 'parameter_group_name', toTargetAttr: 'name' }],
      },
      {
        whenEdgeKind: 'attach',
        direction: 'outbound',
        toResourceType: 'aws_kms_key',
        apply: [{ setArg: 'kms_key_id', toTargetAttr: 'arn' }],
      },
    ],
    autoResolveRules: [
      {
        requiredArg: 'db_subnet_group_name',
        acceptsResourceTypes: ['aws_db_subnet_group'],
        search: [{ type: 'connected_edges', edgeKind: 'attach' }],
        onMissing: {
          level: 'warning',
          message: 'RDS instance has no subnet group configured',
          fixHint: 'Connect to a DB subnet group or specify db_subnet_group_name',
        },
      },
    ],
  },
};
