/**
 * HCL Renderer - Generates Terraform HCL code from resolved graph
 *
 * This module:
 * - Renders resource blocks with proper argument formatting
 * - Handles nested blocks (ebs_block_device, network_interface, etc.)
 * - Formats Terraform references vs literals correctly
 * - Generates association resources
 * - Produces clean, idiomatic HCL output
 */

import type { GraphNode, AssociatedResource } from "./types";

export class HCLRenderer {
  /**
   * Render all nodes to main.tf content
   */
  renderMainTf(nodes: Map<string, GraphNode>): string {
    const lines: string[] = [];

    // Header comment
    lines.push("# Generated by CloudForge");
    lines.push("# https://github.com/yourusername/cloudforge");
    lines.push("");

    // Render each resource
    for (const node of nodes.values()) {
      const hcl = this.renderResource(node);
      if (hcl) {
        lines.push(hcl);
        lines.push("");
      }

      // Render associated resources (e.g., attachments)
      for (const associated of node.associatedResources) {
        const associatedHcl = this.renderAssociatedResource(associated);
        lines.push(associatedHcl);
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  /**
   * Render a single resource block
   */
  private renderResource(node: GraphNode): string {
    const lines: string[] = [];
    const resourceType = node.serviceDefinition.terraform_resource;
    const resourceName = node.terraformName;

    lines.push(`resource "${resourceType}" "${resourceName}" {`);

    // Merge explicit properties with resolved args
    const allArgs = this.mergeArgs(node);

    // Render simple arguments and blocks
    for (const [argName, value] of Object.entries(allArgs)) {
      // Check for nested blocks first (objects with keys)
      if (typeof value === 'object' && value !== null && !Array.isArray(value) && Object.keys(value).length > 0) {
        // Render as a block (not using = syntax)
        const blockHcl = this.renderBlock(argName, value, false);
        lines.push(blockHcl);
      } else if (this.isSimpleArg(value)) {
        // Simple arguments (strings, numbers, booleans, arrays)
        const formatted = this.formatValue(value);
        lines.push(`  ${argName} = ${formatted}`);
      }
    }

    // Render blocks from service definition (if not already rendered)
    const blocks = node.serviceDefinition.inputs.blocks || [];
    for (const blockDef of blocks) {
      // Skip if already rendered from merged args
      if (allArgs[blockDef.name]) {
        continue;
      }
      const blockValues = node.diagramNode.properties?.[blockDef.name];
      if (blockValues) {
        const blockHcl = this.renderBlock(blockDef.name, blockValues, blockDef.multiple || false);
        lines.push(blockHcl);
      }
    }

    // Always add tags with Name
    lines.push("");
    lines.push("  tags = {");
    const nodeName = node.diagramNode.name || node.terraformName;
    lines.push(`    Name = "${nodeName}"`);

    // Add user-defined tags
    const customTags = node.diagramNode.tags || {};
    for (const [key, value] of Object.entries(customTags)) {
      if (key !== "Name") {
        lines.push(`    ${key} = "${value}"`);
      }
    }

    lines.push("  }");
    lines.push("}");

    return lines.join("\n");
  }

  /**
   * Render an associated resource (attachment, association, etc.)
   */
  private renderAssociatedResource(resource: AssociatedResource): string {
    const lines: string[] = [];

    lines.push(`resource "${resource.type}" "${resource.name}" {`);

    for (const [argName, value] of Object.entries(resource.args)) {
      const formatted = this.formatValue(value);
      lines.push(`  ${argName} = ${formatted}`);
    }

    lines.push("}");

    return lines.join("\n");
  }

  /**
   * Merge explicit properties with resolved args
   * Handles nested block notation (e.g., launch_template.id)
   */
  private mergeArgs(node: GraphNode): Record<string, any> {
    const merged: Record<string, any> = {};

    // Start with explicit properties from diagram
    if (node.diagramNode.properties) {
      Object.assign(merged, node.diagramNode.properties);
    }

    // Overlay with resolved args (higher precedence)
    for (const [argName, resolved] of node.resolvedArgs.entries()) {
      // Handle dot notation for nested blocks (e.g., launch_template.id)
      if (argName.includes('.')) {
        const [blockName, ...nestedPath] = argName.split('.');
        if (!merged[blockName]) {
          merged[blockName] = {};
        }
        // Set nested value
        let current = merged[blockName];
        for (let i = 0; i < nestedPath.length - 1; i++) {
          if (!current[nestedPath[i]]) {
            current[nestedPath[i]] = {};
          }
          current = current[nestedPath[i]];
        }
        current[nestedPath[nestedPath.length - 1]] = resolved.value;
      } else {
        merged[argName] = resolved.value;
      }
    }

    // Filter out internal fields
    delete merged.name;
    delete merged.tags;

    // Filter out empty/null values
    for (const [key, value] of Object.entries(merged)) {
      if (value === null || value === undefined || value === "") {
        delete merged[key];
      }
    }

    return merged;
  }

  /**
   * Check if value is a simple arg (not a block)
   */
  private isSimpleArg(value: any): boolean {
    if (typeof value === "object" && value !== null) {
      // Arrays and objects need special handling
      return Array.isArray(value) || this.isSimpleObject(value);
    }
    return true;
  }

  /**
   * Check if object is a simple key-value map (not a nested block)
   */
  private isSimpleObject(value: any): boolean {
    // Simple heuristic: if all values are primitives, it's a simple object
    return Object.values(value).every((v) => typeof v !== "object" || v === null);
  }

  /**
   * Format value for HCL output
   */
  private formatValue(value: any): string {
    if (value === null || value === undefined) {
      return "null";
    }

    if (typeof value === "boolean") {
      return value ? "true" : "false";
    }

    if (typeof value === "number") {
      return String(value);
    }

    if (typeof value === "string") {
      // Check if it's a Terraform reference
      if (this.isTerraformReference(value)) {
        return value; // no quotes for references
      }
      // Literal string - escape and quote
      return `"${this.escapeString(value)}"`;
    }

    if (Array.isArray(value)) {
      return this.formatList(value);
    }

    if (typeof value === "object") {
      return this.formatMap(value);
    }

    return String(value);
  }

  /**
   * Check if string is a Terraform reference (aws_*.*.*, var.*, data.*, local.*)
   */
  private isTerraformReference(value: string): boolean {
    const patterns = [
      /^aws_[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+/, // aws_vpc.main.id
      /^azurerm_[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+/, // azurerm_*
      /^google_[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+/, // google_*
      /^var\.[a-zA-Z0-9_]+/, // var.subnet_id
      /^data\.[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+/, // data.aws_ami.latest
      /^local\.[a-zA-Z0-9_]+/, // local.common_tags
    ];

    return patterns.some((pattern) => pattern.test(value));
  }

  /**
   * Escape string for HCL literal
   */
  private escapeString(value: string): string {
    return value
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/\t/g, "\\t");
  }

  /**
   * Format list for HCL
   */
  private formatList(values: any[]): string {
    if (values.length === 0) {
      return "[]";
    }

    const formatted = values.map((v) => this.formatValue(v));

    // Single line if short
    if (formatted.join(", ").length < 60) {
      return `[${formatted.join(", ")}]`;
    }

    // Multi-line if long
    return `[\n    ${formatted.join(",\n    ")}\n  ]`;
  }

  /**
   * Format map/object for HCL
   */
  private formatMap(obj: Record<string, any>): string {
    const entries = Object.entries(obj);

    if (entries.length === 0) {
      return "{}";
    }

    const lines = entries.map(([key, value]) => {
      const formatted = this.formatValue(value);
      return `    ${key} = ${formatted}`;
    });

    return `{\n${lines.join("\n")}\n  }`;
  }

  /**
   * Render a block (nested configuration)
   */
  private renderBlock(blockName: string, blockValue: any, multiple: boolean): string {
    const lines: string[] = [];

    if (multiple && Array.isArray(blockValue)) {
      // Multiple blocks
      for (const item of blockValue) {
        lines.push(`  ${blockName} {`);
        for (const [key, value] of Object.entries(item)) {
          const formatted = this.formatValue(value);
          lines.push(`    ${key} = ${formatted}`);
        }
        lines.push("  }");
      }
    } else if (!Array.isArray(blockValue)) {
      // Single block
      lines.push(`  ${blockName} {`);
      for (const [key, value] of Object.entries(blockValue)) {
        const formatted = this.formatValue(value);
        lines.push(`    ${key} = ${formatted}`);
      }
      lines.push("  }");
    }

    return lines.join("\n");
  }

  /**
   * Render providers.tf (future enhancement)
   */
  renderProvidersTf(providers: Set<string>): string {
    const lines: string[] = [];

    lines.push("# Provider configuration");
    lines.push("");

    for (const provider of providers) {
      if (provider === "aws") {
        lines.push('provider "aws" {');
        lines.push("  region = var.aws_region");
        lines.push("}");
        lines.push("");
      } else if (provider === "azure") {
        lines.push('provider "azurerm" {');
        lines.push("  features {}");
        lines.push("}");
        lines.push("");
      } else if (provider === "gcp") {
        lines.push('provider "google" {');
        lines.push("  project = var.gcp_project");
        lines.push("  region  = var.gcp_region");
        lines.push("}");
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  /**
   * Render variables.tf (future enhancement)
   */
  renderVariablesTf(providers: Set<string>): string {
    const lines: string[] = [];

    lines.push("# Input variables");
    lines.push("");

    if (providers.has("aws")) {
      lines.push('variable "aws_region" {');
      lines.push('  description = "AWS region"');
      lines.push('  type        = string');
      lines.push('  default     = "us-east-1"');
      lines.push("}");
      lines.push("");
    }

    if (providers.has("azure")) {
      lines.push('variable "azure_location" {');
      lines.push('  description = "Azure location"');
      lines.push('  type        = string');
      lines.push('  default     = "eastus"');
      lines.push("}");
      lines.push("");
    }

    if (providers.has("gcp")) {
      lines.push('variable "gcp_project" {');
      lines.push('  description = "GCP project ID"');
      lines.push('  type        = string');
      lines.push("}");
      lines.push("");
      lines.push('variable "gcp_region" {');
      lines.push('  description = "GCP region"');
      lines.push('  type        = string');
      lines.push('  default     = "us-central1"');
      lines.push("}");
      lines.push("");
    }

    return lines.join("\n");
  }
}
