import { ResourceField, AWSResource } from './awsResources';

export const awsResourcesExpanded: AWSResource[] = [
  // ============ COMPUTE ============
  {
    type: 'aws_instance',
    label: 'EC2 Instance',
    description: 'Virtual server in the cloud',
    icon: '/api/icons/aws/Arch_Compute/64/Arch_Amazon-EC2_64.svg',
    category: 'compute',
    fields: [
      { name: 'ami', label: 'AMI ID', type: 'text', required: true, placeholder: 'ami-xxxxx', description: 'Amazon Machine Image ID', group: 'basic' },
      { name: 'instance_type', label: 'Instance Type', type: 'select', required: true, group: 'basic', options: [
        { value: 't2.micro', label: 't2.micro (1 vCPU, 1 GiB)' },
        { value: 't2.small', label: 't2.small (1 vCPU, 2 GiB)' },
        { value: 't2.medium', label: 't2.medium (2 vCPU, 4 GiB)' },
        { value: 't3.micro', label: 't3.micro (2 vCPU, 1 GiB)' },
        { value: 't3.small', label: 't3.small (2 vCPU, 2 GiB)' },
        { value: 't3.medium', label: 't3.medium (2 vCPU, 4 GiB)' },
        { value: 'm5.large', label: 'm5.large (2 vCPU, 8 GiB)' },
        { value: 'm5.xlarge', label: 'm5.xlarge (4 vCPU, 16 GiB)' },
        { value: 'c5.large', label: 'c5.large (2 vCPU, 4 GiB)' },
      ]},
      { name: 'key_name', label: 'Key Pair', type: 'text', placeholder: 'my-key-pair', group: 'basic' },
      { name: 'availability_zone', label: 'Availability Zone', type: 'text', placeholder: 'us-east-1a', group: 'basic' },
      { name: 'monitoring', label: 'Detailed Monitoring', type: 'boolean', defaultValue: false, group: 'advanced' },
      { name: 'tags', label: 'Tags', type: 'tags', defaultValue: {}, group: 'advanced' },
    ],
  },
  {
    type: 'aws_lambda_function',
    label: 'Lambda Function',
    description: 'Serverless compute service',
    icon: '/api/icons/aws/Arch_Compute/64/Arch_AWS-Lambda_64.svg',
    category: 'compute',
  },
  {
    type: 'aws_elastic_beanstalk_application',
    label: 'Elastic Beanstalk',
    description: 'Platform as a Service',
    icon: '/api/icons/aws/Arch_Compute/64/Arch_AWS-Elastic-Beanstalk_64.svg',
    category: 'compute',
  },
  {
    type: 'aws_batch_job_definition',
    label: 'AWS Batch',
    description: 'Batch computing service',
    icon: '/api/icons/aws/Arch_Compute/64/Arch_AWS-Batch_64.svg',
    category: 'compute',
  },
  {
    type: 'aws_apprunner_service',
    label: 'App Runner',
    description: 'Containerized web applications',
    icon: '/api/icons/aws/Arch_Compute/64/Arch_AWS-App-Runner_64.svg',
    category: 'compute',
  },

  // ============ CONTAINERS ============
  {
    type: 'aws_ecs_cluster',
    label: 'ECS Cluster',
    description: 'Container orchestration',
    icon: '/api/icons/aws/Arch_Containers/64/Arch_Amazon-Elastic-Container-Service_64.svg',
    category: 'containers',
  },
  {
    type: 'aws_ecs_service',
    label: 'ECS Service',
    description: 'Run containerized applications',
    icon: '/api/icons/aws/Arch_Containers/64/Arch_Amazon-Elastic-Container-Service_64.svg',
    category: 'containers',
  },
  {
    type: 'aws_eks_cluster',
    label: 'EKS Cluster',
    description: 'Managed Kubernetes',
    icon: '/api/icons/aws/Arch_Containers/64/Arch_Amazon-Elastic-Kubernetes-Service_64.svg',
    category: 'containers',
  },
  {
    type: 'aws_ecr_repository',
    label: 'ECR Repository',
    description: 'Container registry',
    icon: '/api/icons/aws/Arch_Containers/64/Arch_Amazon-Elastic-Container-Registry_64.svg',
    category: 'containers',
  },

  // ============ STORAGE ============
  {
    type: 'aws_s3_bucket',
    label: 'S3 Bucket',
    description: 'Object storage',
    icon: '/api/icons/aws/Arch_Storage/64/Arch_Amazon-Simple-Storage-Service_64.svg',
    category: 'storage',
    fields: [
      { name: 'bucket', label: 'Bucket Name', type: 'text', required: true, placeholder: 'my-bucket', group: 'basic' },
      { name: 'acl', label: 'ACL', type: 'select', group: 'basic', options: [
        { value: 'private', label: 'Private' },
        { value: 'public-read', label: 'Public Read' },
      ]},
      { name: 'versioning', label: 'Enable Versioning', type: 'boolean', defaultValue: false, group: 'basic' },
      { name: 'tags', label: 'Tags', type: 'tags', defaultValue: {}, group: 'advanced' },
    ],
  },
  {
    type: 'aws_ebs_volume',
    label: 'EBS Volume',
    description: 'Block storage for EC2',
    icon: '/api/icons/aws/Arch_Storage/64/Arch_Amazon-Elastic-Block-Store_64.svg',
    category: 'storage',
  },
  {
    type: 'aws_efs_file_system',
    label: 'EFS File System',
    description: 'Elastic file storage',
    icon: '/api/icons/aws/Arch_Storage/64/Arch_Amazon-EFS_64.svg',
    category: 'storage',
  },
  {
    type: 'aws_fsx_windows_file_system',
    label: 'FSx for Windows',
    description: 'Windows file storage',
    icon: '/api/icons/aws/Arch_Storage/64/Arch_Amazon-FSx_64.svg',
    category: 'storage',
  },
  {
    type: 'aws_backup_vault',
    label: 'AWS Backup',
    description: 'Centralized backup',
    icon: '/api/icons/aws/Arch_Storage/64/Arch_AWS-Backup_64.svg',
    category: 'storage',
  },

  // ============ DATABASE ============
  {
    type: 'aws_db_instance',
    label: 'RDS Instance',
    description: 'Managed relational database',
    icon: '/api/icons/aws/Arch_Database/64/Arch_Amazon-RDS_64.svg',
    category: 'database',
    fields: [
      { name: 'engine', label: 'Database Engine', type: 'select', required: true, group: 'basic', options: [
        { value: 'mysql', label: 'MySQL' },
        { value: 'postgres', label: 'PostgreSQL' },
        { value: 'mariadb', label: 'MariaDB' },
        { value: 'oracle-ee', label: 'Oracle' },
        { value: 'sqlserver-ex', label: 'SQL Server' },
      ]},
      { name: 'instance_class', label: 'Instance Class', type: 'select', required: true, group: 'basic', options: [
        { value: 'db.t3.micro', label: 'db.t3.micro' },
        { value: 'db.t3.small', label: 'db.t3.small' },
        { value: 'db.m5.large', label: 'db.m5.large' },
      ]},
      { name: 'allocated_storage', label: 'Storage (GiB)', type: 'number', defaultValue: 20, group: 'basic' },
      { name: 'tags', label: 'Tags', type: 'tags', defaultValue: {}, group: 'advanced' },
    ],
  },
  {
    type: 'aws_dynamodb_table',
    label: 'DynamoDB Table',
    description: 'NoSQL database',
    icon: '/api/icons/aws/Arch_Database/64/Arch_Amazon-DynamoDB_64.svg',
    category: 'database',
  },
  {
    type: 'aws_elasticache_cluster',
    label: 'ElastiCache',
    description: 'In-memory cache',
    icon: '/api/icons/aws/Arch_Database/64/Arch_Amazon-ElastiCache_64.svg',
    category: 'database',
  },
  {
    type: 'aws_rds_cluster',
    label: 'Aurora Cluster',
    description: 'Aurora database cluster',
    icon: '/api/icons/aws/Arch_Database/64/Arch_Amazon-Aurora_64.svg',
    category: 'database',
  },
  {
    type: 'aws_neptune_cluster',
    label: 'Neptune',
    description: 'Graph database',
    icon: '/api/icons/aws/Arch_Database/64/Arch_Amazon-Neptune_64.svg',
    category: 'database',
  },
  {
    type: 'aws_docdb_cluster',
    label: 'DocumentDB',
    description: 'MongoDB-compatible database',
    icon: '/api/icons/aws/Arch_Database/64/Arch_Amazon-DocumentDB_64.svg',
    category: 'database',
  },
  {
    type: 'aws_redshift_cluster',
    label: 'Redshift',
    description: 'Data warehouse',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-Redshift_64.svg',
    category: 'database',
  },

  // ============ NETWORKING ============
  {
    type: 'aws_vpc',
    label: 'VPC',
    description: 'Virtual Private Cloud',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
    category: 'networking',
    isContainer: true,
  },
  {
    type: 'aws_subnet',
    label: 'Subnet',
    description: 'Subnet within VPC',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
    category: 'networking',
  },
  {
    type: 'aws_security_group',
    label: 'Security Group',
    description: 'Virtual firewall',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-Network-Firewall_64.svg',
    category: 'security',
  },
  {
    type: 'aws_lb',
    label: 'Application Load Balancer',
    description: 'Distribute traffic',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Elastic-Load-Balancing_64.svg',
    category: 'networking',
  },
  {
    type: 'aws_route53_zone',
    label: 'Route 53',
    description: 'DNS service',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Amazon-Route-53_64.svg',
    category: 'networking',
  },
  {
    type: 'aws_cloudfront_distribution',
    label: 'CloudFront',
    description: 'Content delivery network',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Amazon-CloudFront_64.svg',
    category: 'networking',
  },
  {
    type: 'aws_api_gateway_rest_api',
    label: 'API Gateway',
    description: 'API management',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Amazon-API-Gateway_64.svg',
    category: 'application',
  },
  {
    type: 'aws_nat_gateway',
    label: 'NAT Gateway',
    description: 'Network address translation',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
    category: 'networking',
  },
  {
    type: 'aws_internet_gateway',
    label: 'Internet Gateway',
    description: 'VPC internet access',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_Amazon-Virtual-Private-Cloud_64.svg',
    category: 'networking',
  },
  {
    type: 'aws_vpn_gateway',
    label: 'VPN Gateway',
    description: 'VPN connection',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_AWS-Site-to-Site-VPN_64.svg',
    category: 'networking',
  },
  {
    type: 'aws_direct_connect',
    label: 'Direct Connect',
    description: 'Dedicated network connection',
    icon: '/api/icons/aws/Arch_Networking-Content-Delivery/64/Arch_AWS-Direct-Connect_64.svg',
    category: 'networking',
  },

  // ============ SECURITY & IDENTITY ============
  {
    type: 'aws_iam_role',
    label: 'IAM Role',
    description: 'Identity and access role',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-Identity-and-Access-Management_64.svg',
    category: 'security',
  },
  {
    type: 'aws_iam_policy',
    label: 'IAM Policy',
    description: 'Permissions policy',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-Identity-and-Access-Management_64.svg',
    category: 'security',
  },
  {
    type: 'aws_iam_user',
    label: 'IAM User',
    description: 'User account',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-Identity-and-Access-Management_64.svg',
    category: 'security',
  },
  {
    type: 'aws_kms_key',
    label: 'KMS Key',
    description: 'Encryption key',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-Key-Management-Service_64.svg',
    category: 'security',
  },
  {
    type: 'aws_secretsmanager_secret',
    label: 'Secrets Manager',
    description: 'Secrets management',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-Secrets-Manager_64.svg',
    category: 'security',
  },
  {
    type: 'aws_wafv2_web_acl',
    label: 'WAF Web ACL',
    description: 'Web application firewall',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-WAF_64.svg',
    category: 'security',
  },
  {
    type: 'aws_guardduty_detector',
    label: 'GuardDuty',
    description: 'Threat detection',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_Amazon-GuardDuty_64.svg',
    category: 'security',
  },
  {
    type: 'aws_shield_protection',
    label: 'AWS Shield',
    description: 'DDoS protection',
    icon: '/api/icons/aws/Arch_Security-Identity-Compliance/64/Arch_AWS-Shield_64.svg',
    category: 'security',
  },

  // ============ ANALYTICS ============
  {
    type: 'aws_kinesis_stream',
    label: 'Kinesis Data Streams',
    description: 'Real-time data streaming',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-Kinesis-Data-Streams_64.svg',
    category: 'analytics',
  },
  {
    type: 'aws_kinesis_firehose_delivery_stream',
    label: 'Kinesis Firehose',
    description: 'Data delivery to destinations',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-Data-Firehose_64.svg',
    category: 'analytics',
  },
  {
    type: 'aws_athena_database',
    label: 'Athena',
    description: 'Serverless query service',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-Athena_64.svg',
    category: 'analytics',
  },
  {
    type: 'aws_glue_catalog_database',
    label: 'AWS Glue',
    description: 'ETL service',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_AWS-Glue_64.svg',
    category: 'analytics',
  },
  {
    type: 'aws_emr_cluster',
    label: 'EMR Cluster',
    description: 'Big data processing',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-EMR_64.svg',
    category: 'analytics',
  },
  {
    type: 'aws_quicksight_account',
    label: 'QuickSight',
    description: 'Business intelligence',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-QuickSight_64.svg',
    category: 'analytics',
  },
  {
    type: 'aws_opensearch_domain',
    label: 'OpenSearch',
    description: 'Search and analytics',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-OpenSearch-Service_64.svg',
    category: 'analytics',
  },
  {
    type: 'aws_msk_cluster',
    label: 'MSK (Kafka)',
    description: 'Managed Apache Kafka',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-Managed-Streaming-for-Apache-Kafka_64.svg',
    category: 'analytics',
  },

  // ============ APP INTEGRATION ============
  {
    type: 'aws_sns_topic',
    label: 'SNS Topic',
    description: 'Pub/sub messaging',
    icon: '/api/icons/aws/Arch_App-Integration/64/Arch_Amazon-Simple-Notification-Service_64.svg',
    category: 'application',
  },
  {
    type: 'aws_sqs_queue',
    label: 'SQS Queue',
    description: 'Message queue',
    icon: '/api/icons/aws/Arch_App-Integration/64/Arch_Amazon-Simple-Queue-Service_64.svg',
    category: 'application',
  },
  {
    type: 'aws_eventbridge_rule',
    label: 'EventBridge',
    description: 'Event bus',
    icon: '/api/icons/aws/Arch_App-Integration/64/Arch_Amazon-EventBridge_64.svg',
    category: 'application',
  },
  {
    type: 'aws_sfn_state_machine',
    label: 'Step Functions',
    description: 'Workflow orchestration',
    icon: '/api/icons/aws/Arch_App-Integration/64/Arch_AWS-Step-Functions_64.svg',
    category: 'application',
  },

  // ============ AI/ML ============
  {
    type: 'aws_sagemaker_notebook_instance',
    label: 'SageMaker',
    description: 'Machine learning platform',
    icon: '/api/icons/aws/Arch_Analytics/64/Arch_Amazon-SageMaker_64.svg',
    category: 'other',
  },
  {
    type: 'aws_bedrock_model',
    label: 'Amazon Bedrock',
    description: 'Foundation models',
    icon: '/api/icons/aws/Arch_Artificial-Intelligence/64/Arch_Amazon-Bedrock_64.svg',
    category: 'other',
  },
  {
    type: 'aws_rekognition',
    label: 'Rekognition',
    description: 'Image and video analysis',
    icon: '/api/icons/aws/Arch_Artificial-Intelligence/64/Arch_Amazon-Rekognition_64.svg',
    category: 'other',
  },

  // ============ MANAGEMENT & GOVERNANCE ============
  {
    type: 'aws_cloudwatch_log_group',
    label: 'CloudWatch Logs',
    description: 'Log management',
    icon: '/api/icons/aws/Arch_Management-Governance/64/Arch_Amazon-CloudWatch_64.svg',
    category: 'other',
  },
  {
    type: 'aws_cloudwatch_metric_alarm',
    label: 'CloudWatch Alarm',
    description: 'Monitoring alerts',
    icon: '/api/icons/aws/Arch_Management-Governance/64/Arch_Amazon-CloudWatch_64.svg',
    category: 'other',
  },
  {
    type: 'aws_cloudtrail',
    label: 'CloudTrail',
    description: 'Audit and compliance',
    icon: '/api/icons/aws/Arch_Management-Governance/64/Arch_AWS-CloudTrail_64.svg',
    category: 'other',
  },
  {
    type: 'aws_config_configuration_recorder',
    label: 'AWS Config',
    description: 'Resource inventory',
    icon: '/api/icons/aws/Arch_Management-Governance/64/Arch_AWS-Config_64.svg',
    category: 'other',
  },
  {
    type: 'aws_systems_manager_parameter',
    label: 'Systems Manager',
    description: 'Parameter store',
    icon: '/api/icons/aws/Arch_Management-Governance/64/Arch_AWS-Systems-Manager_64.svg',
    category: 'other',
  },

  // ============ DEVELOPER TOOLS ============
  {
    type: 'aws_codecommit_repository',
    label: 'CodeCommit',
    description: 'Git repository',
    icon: '/api/icons/aws/Arch_Developer-Tools/64/Arch_AWS-CodeCommit_64.svg',
    category: 'other',
  },
  {
    type: 'aws_codebuild_project',
    label: 'CodeBuild',
    description: 'Build and test code',
    icon: '/api/icons/aws/Arch_Developer-Tools/64/Arch_AWS-CodeBuild_64.svg',
    category: 'other',
  },
  {
    type: 'aws_codepipeline',
    label: 'CodePipeline',
    description: 'CI/CD pipeline',
    icon: '/api/icons/aws/Arch_Developer-Tools/64/Arch_AWS-CodePipeline_64.svg',
    category: 'other',
  },
  {
    type: 'aws_codedeploy_app',
    label: 'CodeDeploy',
    description: 'Automated deployment',
    icon: '/api/icons/aws/Arch_Developer-Tools/64/Arch_AWS-CodeDeploy_64.svg',
    category: 'other',
  },
];

